In [5]:
import pandas as pd
df = pd.read_csv("./datasets/Traffic_Count_Locations_with_LONG_LAT.csv")
df.head(5)

,X,Y,FID,OBJECTID,TFM_ID,TFM_DESC,TFM_TYP_DE,MOVEMENT_T,SITE_DESC,ROAD_NBR,DECLARED_R,LOCAL_ROAD,DATA_SRC_C,DATA_SOURC,TIME_CATEG,YEAR_SINCE,LAST_YEAR,AADT_ALLVE,AADT_TRUCK,PER_TRUCKS
0,144.250614,-36.779313,7001,7301,7656,CALDER HWY NE OF OAK ST,INTERSECTION,All Moves,CALDER HWY & OAK ST,2530,CALDER HIGHWAY,HIGH STREET,TMVMT,Manual,Greater than 10 Years,19,1997,7700,330,0.04
1,145.356779,-37.835309,7002,7302,29406,MT DANDENONG RD S BD SE OF UPALONG RD,INTERSECTION,All Moves,MT DANDENONG RD SE OF UPALONG RD,4991,MOUNT DANDENONG ROAD,MOUNT DANDENONG TOURIST ROAD,APARX,Classification,Greater than 10 Years,16,2000,1900,0,0.00
2,144.988844,-37.824629,7003,7303,22676,SWAN ST W BD E OF PUNT RD,INTERSECTION,All Moves,PUNT RD LEFT TURN TO SWAN ST OD:12,2080,HODDLE HIGHWAY,PUNT ROAD,MOTSV,Manual,Greater than 10 Years,23,1993,15000,630,0.04
3,144.932442,-37.803783,7004,7304,27902,DYNON RD W BD E OF RADCLIFFE ST,INTERSECTION,All Moves,DYNON RD & RADCLIFFE ST,5035,DYNON ROAD,DYNON ROAD,TMVMT,Manual,Greater than 10 Years,19,1997,12000,1300,0.10
4,145.030601,-37.660502,7005,7305,10935,DALTON RD N of CHILDS RD,INTERSECTION,All Moves,CHILDS RD & DALTON RD,5605,DALTON ROAD,DALTON ROAD,TMVMT,Manual,Greater than 10 Years,19,1997,12000,600,0.05

In [7]:
pd.Categorical(df["TIME_CATEG"])

['Greater than 10 Years', 'Greater than 10 Years', 'Greater than 10 Years', 'Greater than 10 Years', 'Greater than 10 Years', ..., 'Greater than 10 Years', 'Greater than 10 Years', 'Greater than 10 Years', 'Greater than 10 Years', 'Greater than 10 Years']
Length: 57947
Categories (4, object): ['Between 2 and 5 Years', 'Between 5 and 10 Years', 'Greater than 10 Years', 'Less than 2 Years']

In [8]:
pd.Categorical(df["AADT_ALLVE"])

[7700, 1900, 15000, 12000, 12000, ..., 0, 0, 18000, 0, 0]
Length: 57947
Categories (292, int64): [0, 10, 20, 30, ..., 111000, 112000, 120000, 123000]

In [ ]:
df[]